// samples/angular/token-refresh/src/app/app.ts
// @snippet:step3:start
// @description Display token status and trigger manual refresh
import { Component, inject, OnInit, signal } from "@angular/core";
import { OidcSecurityService } from "angular-auth-oidc-client";

@Component({
  selector: "app-root",
  standalone: true,
  template: `
    <h1>SecureAuth Token Refresh Demo</h1>
    @if (isLoading()) {
      <p>Loading...</p>
    } @else if (errorMessage()) {
      <div style="color: red">
        <p>Error: {{ errorMessage() }}</p>
        @if (errorHint()) {
          <p>{{ errorHint() }}</p>
        }
        <button (click)="login()">Try again</button>
      </div>
    } @else if (isAuthenticated()) {
      <p>Welcome, {{ userData()?.given_name }}</p>
      <p>Token expires at: {{ tokenExpiry() }}</p>
      <button (click)="refresh()">Refresh token now</button>
      <br />
      <br />
      <button (click)="logout()">Sign out</button>
    } @else {
      <button (click)="login()">Sign in</button>
    }
  `,
})
export class App implements OnInit {
  private auth = inject(OidcSecurityService);

  isLoading = signal(true);
  isAuthenticated = signal(false);
  userData = signal<any>(null);
  tokenExpiry = signal("unknown");
  errorMessage = signal("");
  errorHint = signal("");

  ngOnInit() {
    const params = new URLSearchParams(window.location.search);
    const error = params.get("error");
    if (error) {
      this.isLoading.set(false);
      this.errorMessage.set(params.get("error_description") || error);
      this.errorHint.set(params.get("error_hint") || "");
      return;
    }

    this.auth.checkAuth().subscribe({
      next: (response) => {
        this.updateFromResponse(response);
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error("checkAuth error:", err);
        this.errorMessage.set(err?.message || "Authentication failed");
        this.isLoading.set(false);
      },
    });
  }

  login() {
    this.auth.authorize();
  }

  refresh() {
    this.auth.forceRefreshSession().subscribe({
      next: (response) => this.updateFromResponse(response),
      error: (err) => console.error("refresh error:", err),
    });
  }

  logout() {
    this.auth.logoff().subscribe({
      error: (err) => console.error("logoff error:", err),
    });
  }

  private updateFromResponse(response: {
    isAuthenticated: boolean;
    userData: any;
    accessToken?: string;
  }) {
    this.isAuthenticated.set(response.isAuthenticated);
    this.userData.set(response.userData);
    if (response.isAuthenticated && response.accessToken) {
      try {
        const payload = JSON.parse(atob(response.accessToken.split(".")[1]));
        if (payload.exp) {
          this.tokenExpiry.set(new Date(payload.exp * 1000).toLocaleTimeString());
        }
      } catch {
        // ignore parse errors
      }
    }
  }
}
// @snippet:step3:end

// samples/react/token-refresh/src/App.tsx
// @snippet:step1:start
// @description Import the OIDC library
import { AuthProvider, useAuth } from "react-oidc-context";
// @snippet:step1:end

// @snippet:step2:start
// @description Request offline_access scope to receive a refresh token
const oidcConfig = {
  authority: import.meta.env.ISSUER_URL,
  client_id: import.meta.env.CLIENT_ID,
  redirect_uri: import.meta.env.REDIRECT_URI,
  scope: import.meta.env.SCOPES,
};
// @snippet:step2:end

// @snippet:step3:start
// @description Display token status and trigger manual refresh
function TokenStatus() {
  const auth = useAuth();

  if (auth.isLoading) {
    return <p>Loading...</p>;
  }

  if (auth.error) {
    const hint = new URLSearchParams(window.location.search).get("error_hint");
    return (
      <div style={{ color: "red" }}>
        <p>Error: {auth.error.message}</p>
        {hint && <p>{hint}</p>}
        <button onClick={() => auth.signinRedirect()}>Try again</button>
      </div>
    );
  }

  if (!auth.isAuthenticated) {
    return <button onClick={() => auth.signinRedirect()}>Sign in</button>;
  }

  const expiresAt = auth.user?.expires_at
    ? new Date(auth.user.expires_at * 1000).toLocaleTimeString()
    : "unknown";

  const handleRefresh = async () => {
    try {
      await auth.signinSilent();
    } catch (error) {
      console.error("Token refresh failed:", error);
    }
  };

  return (
    <div>
      <p>Welcome, {auth.user?.profile.given_name}</p>
      <p>Token expires at: {expiresAt}</p>
      <button onClick={handleRefresh}>Refresh token now</button>
    </div>
  );
}
// @snippet:step3:end

// @snippet:step4:start
// @description Wrap your app with AuthProvider
export default function App() {
  return (
    <AuthProvider {...oidcConfig}>
      <h1>SecureAuth Token Refresh Demo</h1>
      <TokenStatus />
    </AuthProvider>
  );
}
// @snippet:step4:end
